buildscript {
    repositories {
        mavenCentral()
    }
}

allprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'
}

configure(subprojects) {
    apply plugin: 'java-library'
    sourceCompatibility = 17
    compileJava {
        options.encoding = 'UTF-8'
    }
    
    repositories {
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://oss.sonatype.org/content/repositories/releases/' }
    }
}

project(':core') {
    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
    }
}

project(':desktop') {
    dependencies {
        implementation project(':core')
        api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}
