plugins {
    id 'java'
    id 'application'
}

group = 'com.wargame'
version = '0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

ext {
    libgdxVersion = '1.12.1'
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$libgdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$libgdxVersion:natives-desktop"
}

application {
    mainClass = 'com.wargame.game.desktop.DesktopLauncher'
}
